autocmd FileType python setlocal noexpandtab
autocmd FileType python setlocal tabstop=4

set autoindent
set copyindent
set noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set number
set noswapfile
set encoding=utf-8
set ruler
set wrap
set smarttab
set showmatch
set smartcase
set autochdir
set expandtab

